from __future__ import annotations

import re
from pathlib import Path

from video_analysis_pipeline.models import SubtitleSpan
from video_analysis_pipeline.subtitle_ocr import normalize_subtitle_text


_TIME_RANGE_PATTERN = re.compile(
    r"^\s*(\d{2}:\d{2}:\d{2}[,.]\d{1,3})\s*-->\s*(\d{2}:\d{2}:\d{2}[,.]\d{1,3})(?:\s+.*)?$"
)
_HTML_TAG_PATTERN = re.compile(r"<[^>]+>")
_BRACE_STYLE_PATTERN = re.compile(r"\{[^}]*\}")
_LEADING_BOILERPLATE_PATTERNS = (
    "ai生成",
    "ai 生成",
    "generatedbyai",
    "generated by ai",
    "aigenerated",
    "ai generated",
)


def parse_srt_file(srt_path: Path) -> list[SubtitleSpan]:
    if not srt_path.exists():
        raise FileNotFoundError(f"SRT file not found: {srt_path}")

    content = srt_path.read_text(encoding="utf-8-sig")
    blocks = re.split(r"\r?\n\s*\r?\n", content.strip())
    spans: list[SubtitleSpan] = []

    for block_number, raw_block in enumerate(blocks, start=1):
        lines = [line.strip() for line in raw_block.splitlines() if line.strip()]
        if len(lines) < 2:
            continue

        raw_index: int | None = None
        if lines[0].isdigit():
            raw_index = int(lines[0])
            lines = lines[1:]

        if not lines:
            continue

        time_match = _TIME_RANGE_PATTERN.match(lines[0])
        if not time_match:
            continue

        start_ms = _parse_srt_timestamp(time_match.group(1))
        end_ms = _parse_srt_timestamp(time_match.group(2))
        text = _clean_srt_text(lines[1:])
        normalized_text = normalize_subtitle_text(text)
        if not normalized_text:
            continue

        spans.append(
            SubtitleSpan(
                text=text,
                normalized_text=normalized_text,
                start_ms=start_ms,
                end_ms=max(start_ms + 1, end_ms),
                confidence=1.0,
                frame_count=1,
                source="srt",
                raw_index=raw_index if raw_index is not None else block_number,
                source_texts=[text],
            )
        )

    return _filter_leading_boilerplate_spans(spans)


def discover_srt_path(
    source_mp4: Path,
    source_srt: Path | None = None,
    srt_name: str | None = None,
) -> Path | None:
    if source_srt is not None:
        if not source_srt.exists():
            raise FileNotFoundError(f"SRT file not found: {source_srt}")
        return source_srt

    search_dir = source_mp4.parent
    if srt_name:
        named_srt = search_dir / srt_name
        if not named_srt.exists():
            raise FileNotFoundError(f"SRT file not found: {named_srt}")
        return named_srt

    exact_match = source_mp4.with_suffix(".srt")
    if exact_match.exists():
        return exact_match

    stem_matches = sorted(search_dir.glob(f"{source_mp4.stem}*.srt"))
    if len(stem_matches) == 1:
        return stem_matches[0]
    if len(stem_matches) > 1:
        raise RuntimeError(
            f"Multiple SRT files match {source_mp4.name}: "
            + ", ".join(path.name for path in stem_matches)
        )

    all_srts = sorted(search_dir.glob("*.srt"))
    if len(all_srts) == 1:
        return all_srts[0]
    if len(all_srts) > 1:
        raise RuntimeError(
            f"Multiple SRT files found beside {source_mp4.name}; "
            "please pass --source-srt or --srt-name explicitly."
        )

    return None


def _parse_srt_timestamp(value: str) -> int:
    normalized = value.replace(",", ".")
    hours_text, minutes_text, seconds_text = normalized.split(":")
    seconds_whole_text, milliseconds_text = seconds_text.split(".")
    milliseconds = int(milliseconds_text.ljust(3, "0")[:3])
    total_ms = (
        int(hours_text) * 3_600_000
        + int(minutes_text) * 60_000
        + int(seconds_whole_text) * 1_000
        + milliseconds
    )
    return total_ms


def _clean_srt_text(lines: list[str]) -> str:
    cleaned_lines = []
    for line in lines:
        cleaned = _HTML_TAG_PATTERN.sub("", line)
        cleaned = _BRACE_STYLE_PATTERN.sub("", cleaned)
        cleaned = " ".join(cleaned.split()).strip()
        if cleaned:
            cleaned_lines.append(cleaned)
    return " ".join(cleaned_lines).strip()


def _filter_leading_boilerplate_spans(spans: list[SubtitleSpan]) -> list[SubtitleSpan]:
    first_content_index = 0
    while first_content_index < len(spans):
        candidate = spans[first_content_index]
        if not _is_leading_boilerplate(candidate):
            break
        first_content_index += 1
    return spans[first_content_index:]


def _is_leading_boilerplate(span: SubtitleSpan) -> bool:
    normalized_compact = span.normalized_text.replace(" ", "")
    raw_compact = span.text.casefold().replace(" ", "")
    return any(
        pattern.replace(" ", "") in normalized_compact or pattern.replace(" ", "") in raw_compact
        for pattern in _LEADING_BOILERPLATE_PATTERNS
    )
