from __future__ import annotations

import re
from pathlib import Path

from video_analysis_pipeline.models import SubtitleSpan
from video_analysis_pipeline.subtitle_ocr import normalize_subtitle_text


_TIME_RANGE_PATTERN = re.compile(
    r"^\s*(\d{2}:\d{2}:\d{2}[,.]\d{1,3})\s*-->\s*(\d{2}:\d{2}:\d{2}[,.]\d{1,3})(?:\s+.*)?$"
)
_HTML_TAG_PATTERN = re.compile(r"<[^>]+>")
_BRACE_STYLE_PATTERN = re.compile(r"\{[^}]*\}")
_LEADING_BOILERPLATE_PATTERNS = (
    "ai生成",
    "ai 生成",
    "generatedbyai",
    "generated by ai",
    "aigenerated",
    "ai generated",
)


def parse_srt_file(srt_path: Path) -> list[SubtitleSpan]:
    if not srt_path.exists():
        raise FileNotFoundError(f"SRT file not found: {srt_path}")

    content = srt_path.read_text(encoding="utf-8-sig")
    spans: list[SubtitleSpan] = []

    for block_number, (raw_index, time_line, text_lines) in enumerate(_iter_srt_blocks(content), start=1):
        time_match = _TIME_RANGE_PATTERN.match(time_line)
        if not time_match:
            continue

        start_ms = _parse_srt_timestamp(time_match.group(1))
        end_ms = _parse_srt_timestamp(time_match.group(2))
        text = _clean_srt_text(text_lines)
        normalized_text = normalize_subtitle_text(text)
        if not normalized_text:
            continue

        spans.append(
            SubtitleSpan(
                text=text,
                normalized_text=normalized_text,
                start_ms=start_ms,
                end_ms=max(start_ms + 1, end_ms),
                confidence=1.0,
                frame_count=1,
                source="srt",
                raw_index=raw_index if raw_index is not None else block_number,
                source_texts=[text],
            )
        )

    normalized_spans = _sort_subtitle_spans_chronologically(spans)
    normalized_spans = _normalize_leading_title_span(normalized_spans)
    return _filter_leading_boilerplate_spans(normalized_spans)


def _iter_srt_blocks(content: str) -> list[tuple[int | None, str, list[str]]]:
    lines = content.splitlines()
    blocks: list[tuple[int | None, str, list[str]]] = []
    index = 0

    while index < len(lines):
        current_line = lines[index].strip()
        if not current_line:
            index += 1
            continue

        raw_index: int | None = None
        time_line_index = index
        if current_line.isdigit() and index + 1 < len(lines) and _TIME_RANGE_PATTERN.match(lines[index + 1].strip()):
            raw_index = int(current_line)
            time_line_index = index + 1
            index += 2
        elif _TIME_RANGE_PATTERN.match(current_line):
            index += 1
        else:
            index += 1
            continue

        time_line = lines[time_line_index].strip()
        text_lines: list[str] = []
        while index < len(lines):
            stripped_line = lines[index].strip()
            if not stripped_line:
                index += 1
                break
            if stripped_line.isdigit() and index + 1 < len(lines) and _TIME_RANGE_PATTERN.match(lines[index + 1].strip()):
                break
            if _TIME_RANGE_PATTERN.match(stripped_line):
                break
            text_lines.append(lines[index])
            index += 1

        blocks.append((raw_index, time_line, text_lines))

    return blocks


def discover_srt_path(
    source_mp4: Path,
    source_srt: Path | None = None,
    srt_name: str | None = None,
) -> Path | None:
    if source_srt is not None:
        if not source_srt.exists():
            raise FileNotFoundError(f"SRT file not found: {source_srt}")
        return source_srt

    search_dir = source_mp4.parent
    if srt_name:
        named_srt = search_dir / srt_name
        if not named_srt.exists():
            raise FileNotFoundError(f"SRT file not found: {named_srt}")
        return named_srt

    exact_match = source_mp4.with_suffix(".srt")
    if exact_match.exists():
        return exact_match

    stem_matches = sorted(search_dir.glob(f"{source_mp4.stem}*.srt"))
    if len(stem_matches) == 1:
        return stem_matches[0]
    if len(stem_matches) > 1:
        raise RuntimeError(
            f"Multiple SRT files match {source_mp4.name}: "
            + ", ".join(path.name for path in stem_matches)
        )

    all_srts = sorted(search_dir.glob("*.srt"))
    if len(all_srts) == 1:
        return all_srts[0]
    if len(all_srts) > 1:
        raise RuntimeError(
            f"Multiple SRT files found beside {source_mp4.name}; "
            "please pass --source-srt or --srt-name explicitly."
        )

    return None


def _parse_srt_timestamp(value: str) -> int:
    normalized = value.replace(",", ".")
    hours_text, minutes_text, seconds_text = normalized.split(":")
    seconds_whole_text, milliseconds_text = seconds_text.split(".")
    milliseconds = int(milliseconds_text.ljust(3, "0")[:3])
    total_ms = (
        int(hours_text) * 3_600_000
        + int(minutes_text) * 60_000
        + int(seconds_whole_text) * 1_000
        + milliseconds
    )
    return total_ms


def _clean_srt_text(lines: list[str]) -> str:
    cleaned_lines = []
    for line in lines:
        cleaned = _HTML_TAG_PATTERN.sub("", line)
        cleaned = _BRACE_STYLE_PATTERN.sub("", cleaned)
        cleaned = " ".join(cleaned.split()).strip()
        if cleaned:
            cleaned_lines.append(cleaned)
    return " ".join(cleaned_lines).strip()


def _filter_leading_boilerplate_spans(spans: list[SubtitleSpan]) -> list[SubtitleSpan]:
    first_content_index = 0
    while first_content_index < len(spans):
        candidate = spans[first_content_index]
        if not _is_leading_boilerplate(candidate):
            break
        first_content_index += 1
    return spans[first_content_index:]


def _sort_subtitle_spans_chronologically(spans: list[SubtitleSpan]) -> list[SubtitleSpan]:
    return sorted(
        spans,
        key=lambda item: (
            item.start_ms,
            item.end_ms,
            item.raw_index if item.raw_index is not None else 1_000_000,
        ),
    )


def _normalize_leading_title_span(spans: list[SubtitleSpan]) -> list[SubtitleSpan]:
    if len(spans) < 2:
        return spans

    first_span = spans[0]
    second_span = spans[1]
    if first_span.start_ms != 0:
        return spans
    if first_span.end_ms < second_span.start_ms:
        return spans

    first_span.end_ms = max(first_span.start_ms + 1, second_span.start_ms - 1)
    return spans


def _is_leading_boilerplate(span: SubtitleSpan) -> bool:
    normalized_compact = span.normalized_text.replace(" ", "")
    raw_compact = span.text.casefold().replace(" ", "")
    return any(
        pattern.replace(" ", "") in normalized_compact or pattern.replace(" ", "") in raw_compact
        for pattern in _LEADING_BOILERPLATE_PATTERNS
    )
